-- WATCHED PAIRS
INSERT INTO PLUTO_INSTRUMENTS(ID, TICKER) VALUES (1, 'ETHBTC');
INSERT INTO PLUTO_INSTRUMENTS(ID, TICKER) VALUES (2, 'IOTBTC');
INSERT INTO PLUTO_INSTRUMENTS(ID, TICKER) VALUES (3, 'XMRBTC');

INSERT INTO PLUTO_BASKETS(BASKET_ID, LABEL) VALUES (1, 'BASIC');
INSERT INTO PLUTO_WEIGHTS(ID, CURRENCY, WEIGHT, BASKET_ID) VALUES (1, 'BTC', 0.5, 1);
INSERT INTO PLUTO_WEIGHTS(ID, CURRENCY, WEIGHT, BASKET_ID) VALUES (2, 'IOT', 0.5, 1);
INSERT INTO PLUTO_POSITIONS(ID, CURRENCY, QUANTITY, TIMESTAMP, BASKET_ID) VALUES (1, 'BTC', 0.00732221, NULL, 1);
INSERT INTO PLUTO_POSITIONS(ID, CURRENCY, QUANTITY, TIMESTAMP, BASKET_ID) VALUES (2, 'IOT', 327.19302672, NULL, 1);